name: CI

on:
  push:
    branches: [ master, 1.x ]
  pull_request:
    branches: [ master, 1.x ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      os: 'ubuntu-latest'
      version: '14, 16, 18, 20, 22'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
